### ISSUE TITLE
After the tezos upgrade I encountered a problem

### ISSUE THREAD

**Issue by focusshell** [cryptiumlabs/backerei#37] opened 2019-05-31 00:11 UTC
![image](https://user-images.githubusercontent.com/42060860/58672911-a9882a00-837b-11e9-90c1-5875d6d2e2b5.png)

**Comment by cwgoes** [comment] 2019-06-01 18:34
Closing as a duplicate of https://github.com/cryptiumlabs/backerei/issues/38.

**Closed by cwgoes** 2019-06-01 18:34 UTC
