### ISSUE TITLE
Storage Error on Alphanet

### ISSUE THREAD

**Issue by tmlee** [cryptiumlabs/backerei#29] opened 2019-02-08 06:22 UTC
Thanks for writing up this awesome library to solve the problem of making sure of consistent payouts by a Tezos Baker.

I am still experimenting with running a baker on Alphanet, and wanted to give this a go.

I've read some the issues here and was able to adjust the cycle rate etc. (correctly i assumed for Alphanet) but I am stuck with the following error when running `payout`

`
(StatusCodeException (Response {responseStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("content-length","202"),("content-type","application/json")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "[{\"kind\":\"permanent\",\"id\":\"proto.003-PsddFKi3.context.storage_error\",\"missing_key\":[\"contracts\",\"index\",\"ed25519\",\"f0\",\"49\",\"28\",\"c7\",\"ac\",\"1bb622b03be5f73ced95e320599b10\",\"balance\"],\"function\":\"get\"}]\n"))
`

Doesn't sound good as i read from the docs its a corrupted data store (according to https://tezos.gitlab.io/alphanet/api/errors.html)
Node is still working but i wonder how to recover from this state to get Backerei working

Thanks!

**Comment by cwgoes** [comment] 2019-02-08 07:23
Hmm, I haven't seen that before.

Have you edited `~/.backerei.yaml` to set the appropriate constants (cycleLength, snapshotInterval) for the alphanet?

**Comment by tmlee** [comment] 2019-02-08 09:52
@cwgoes thanks for the response, below is the current yml file

```
fromAddress: tz...
fromAccountName: payout
databasePath: /home/user/.backerei.json
fee:
  denominator: 10
  numerator: 1
cycleLength: 2048
clientPath: /usr/local/bin/tezos-client
clientConfigFile: /home/user/.tezos-client/config
startingCycle: 47
host: 127.0.0.1
snapshotInterval: 128
bakerAddress: tz...
port: 8732
```

I've set the cycle value and snapshotinterval according to one of the response in the issues.

**Comment by cwgoes** [comment] 2019-02-09 04:29
Those configuration parameters look correct to me. If your datastore is indeed corrupted, I suggest stopping `backerei`, stopping `tezos-node`, wiping your data directory, resyncing your node to the alphanet, and running `backerei payout` again. `backerei` should deal just fine with that.

**Comment by tmlee** [comment] 2019-02-15 08:26
No luck, deleted the storage and resync from zero and still getting the same error unfortunately

**Comment by cwgoes** [comment] 2019-02-23 18:47
Unfortunately I cannot reproduce this at all. Maybe there's a bug in the alphanet codebase?

**Comment by cwgoes** [comment] 2019-03-15 14:17
Closing for now, but reopen if additional debugging is necessary.

**Closed by cwgoes** 2019-03-15 14:17 UTC
